CREATE TABLE company (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    name VARCHAR(160) NOT NULL DEFAULT '',
    document VARCHAR(32) NOT NULL DEFAULT '',
    zip VARCHAR(9) NOT NULL DEFAULT '',
    street VARCHAR(160) NOT NULL DEFAULT '',
    number VARCHAR(20) NOT NULL DEFAULT '',
    complement VARCHAR(120) NOT NULL DEFAULT '',
    district VARCHAR(120) NOT NULL DEFAULT '',
    city VARCHAR(120) NOT NULL DEFAULT '',
    state VARCHAR(2) NOT NULL DEFAULT '',
    phone VARCHAR(32) NOT NULL DEFAULT '',
    email VARCHAR(160) NOT NULL DEFAULT '',
    logo TEXT NOT NULL DEFAULT '',
    logo_width INT NOT NULL DEFAULT 0,
    logo_height INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO company (id) VALUES (1);
